import bcrypt from 'bcrypt'; import User from '../models/User.js'; import { ApiError,asyncHandler,ok } from '../utils/api.js'; import { accessToken,refreshToken,verifyRefresh,refreshCookie } from '../utils/tokens.js';
const issue=async(res,u)=>{const r=refreshToken(u);u.refreshTokens=[...(u.refreshTokens||[]).filter(x=>x.expiresAt>new Date()),{token:r,expiresAt:new Date(Date.now()+6048e5)}];await u.save();res.cookie(process.env.COOKIE_NAME||'fastlance_refresh',r,refreshCookie);return ok(res,{user:u.publicData(),accessToken:accessToken(u)},'Authenticated');};
export const register=asyncHandler(async(req,res)=>{const {name,email,password,role}=req.body; if(!['client','freelancer'].includes(role))throw new ApiError(400,'Role must be client or freelancer');if(await User.exists({email:email.toLowerCase()}))throw new ApiError(409,'Email already registered');const u=await User.create({...req.body,email:email.toLowerCase(),password:await bcrypt.hash(password,12)});return issue(res,u);});
export const login=asyncHandler(async(req,res)=>{const u=await User.findOne({email:req.body.email.toLowerCase()}).select('+password');if(!u||!(await bcrypt.compare(req.body.password,u.password)))throw new ApiError(401,'Invalid email or password');if(u.accountStatus==='suspended')throw new ApiError(403,'Account suspended');return issue(res,u);});
export const refresh=asyncHandler(async(req,res)=>{const t=req.cookies[process.env.COOKIE_NAME||'fastlance_refresh'];if(!t)throw new ApiError(401,'Refresh token required');const p=verifyRefresh(t);const u=await User.findById(p.sub);if(!u||!u.refreshTokens.some(x=>x.token===t))throw new ApiError(401,'Invalid refresh token');return ok(res,{accessToken:accessToken(u)});});
export const logout=asyncHandler(async(req,res)=>{const t=req.cookies[process.env.COOKIE_NAME||'fastlance_refresh'];if(t)await User.updateOne({refreshTokens:t},{$pull:{refreshTokens:{token:t}}});res.clearCookie(process.env.COOKIE_NAME||'fastlance_refresh',refreshCookie);return ok(res,{},'Logged out');});
export const me=(req,res)=>ok(res,{user:req.user.publicData()});
export const updateMe=asyncHandler(async(req,res)=>{const allowed=['name','avatar','bio','headline','company','website','location','skills','professionalTitle','serviceCategories','experience','availability','hourlyRate'];allowed.forEach(k=>{if(req.body[k]!==undefined)req.user[k]=req.body[k];});await req.user.save();ok(res,{user:req.user.publicData()},'Profile updated');});
export const changePassword=asyncHandler(async(req,res)=>{if(!(await bcrypt.compare(req.body.currentPassword,req.user.password)))throw new ApiError(400,'Current password is incorrect');req.user.password=await bcrypt.hash(req.body.newPassword,12);req.user.refreshTokens=[];await req.user.save();ok(res,{},'Password changed');});
